### ISSUE TITLE
functions.R file missing

### ISSUE THREAD

**Issue by ccruizm** [rsankowski/sankowski_et_al_human_CAMs_code#1]
Hi there!

I was trying to implement some of the analyses you employed in your excellent publication, but I noticed some of the custom functions are in the `functions.R`, but this file is not in the repository. Could you please share it?

Thanks in advance!

**Comment by rsankowski** [comment]
Hi Cristian,

Thanks for letting me know - I just add it.

Best,

Roman


Cristian ***@***.***> schrieb am Di. 30. Jan. 2024 um 12:45:

**Comment by ccruizm** [comment]
Thank you, @rsankowski, for the speedy reply and code uploading!
